/**
 * wiki-data.js — Auto-generated lookup tables for wiki-tables.js.
 * Include BEFORE wiki-tables.js:
 *   <script src="../../src/wiki-data.js"></script>
 *   <script src="../../src/wiki-tables.js"></script>
 *
 * POKEDEX: Name → { d: "0XXX" (dex number), t: "type1,type2" (English) }
 * TRAINER_ALIASES: Friendly class name → sprite filename
 */

/* ── Pokédex lookup (name → dex + types) ── */
const POKEDEX = {
  "Bulbasaur": {d:"0001",t:"grass,poison"},
  "Ivysaur": {d:"0002",t:"grass,poison"},
  "Venusaur": {d:"0003",t:"grass,poison"},
  "Charmander": {d:"0004",t:"fire"},
  "Charmeleon": {d:"0005",t:"fire"},
  "Charizard": {d:"0006",t:"fire,flying"},
  "Squirtle": {d:"0007",t:"water"},
  "Wartortle": {d:"0008",t:"water"},
  "Blastoise": {d:"0009",t:"water"},
  "Caterpie": {d:"0010",t:"bug"},
  "Metapod": {d:"0011",t:"bug"},
  "Butterfree": {d:"0012",t:"bug,flying"},
  "Weedle": {d:"0013",t:"bug,poison"},
  "Kakuna": {d:"0014",t:"bug,poison"},
  "Beedrill": {d:"0015",t:"bug,poison"},
  "Pidgey": {d:"0016",t:"normal,flying"},
  "Pidgeotto": {d:"0017",t:"normal,flying"},
  "Pidgeot": {d:"0018",t:"normal,flying"},
  "Rattata": {d:"0019",t:"normal"},
  "Raticate": {d:"0020",t:"normal"},
  "Spearow": {d:"0021",t:"normal,flying"},
  "Fearow": {d:"0022",t:"normal,flying"},
  "Ekans": {d:"0023",t:"poison"},
  "Arbok": {d:"0024",t:"poison"},
  "Pikachu": {d:"0025",t:"electric"},
  "Raichu": {d:"0026",t:"electric"},
  "Sandshrew": {d:"0027",t:"ground"},
  "Sandslash": {d:"0028",t:"ground"},
  "Nidoran♀": {d:"0029",t:"poison"},
  "Nidorina": {d:"0030",t:"poison"},
  "Nidoqueen": {d:"0031",t:"poison,ground"},
  "Nidoran♂": {d:"0032",t:"poison"},
  "Nidorino": {d:"0033",t:"poison"},
  "Nidoking": {d:"0034",t:"poison,ground"},
  "Clefairy": {d:"0035",t:"normal"},
  "Clefable": {d:"0036",t:"normal"},
  "Vulpix": {d:"0037",t:"fire"},
  "Ninetales": {d:"0038",t:"fire"},
  "Jigglypuff": {d:"0039",t:"normal"},
  "Wigglytuff": {d:"0040",t:"normal"},
  "Zubat": {d:"0041",t:"poison,flying"},
  "Golbat": {d:"0042",t:"poison,flying"},
  "Oddish": {d:"0043",t:"grass,poison"},
  "Gloom": {d:"0044",t:"grass,poison"},
  "Vileplume": {d:"0045",t:"grass,poison"},
  "Paras": {d:"0046",t:"bug,grass"},
  "Parasect": {d:"0047",t:"bug,grass"},
  "Venonat": {d:"0048",t:"bug,poison"},
  "Venomoth": {d:"0049",t:"bug,poison"},
  "Diglett": {d:"0050",t:"ground"},
  "Dugtrio": {d:"0051",t:"ground"},
  "Meowth": {d:"0052",t:"normal"},
  "Persian": {d:"0053",t:"normal"},
  "Psyduck": {d:"0054",t:"water"},
  "Golduck": {d:"0055",t:"water"},
  "Mankey": {d:"0056",t:"fighting"},
  "Primeape": {d:"0057",t:"fighting"},
  "Growlithe": {d:"0058",t:"fire"},
  "Arcanine": {d:"0059",t:"fire"},
  "Poliwag": {d:"0060",t:"water"},
  "Poliwhirl": {d:"0061",t:"water"},
  "Poliwrath": {d:"0062",t:"water,fighting"},
  "Abra": {d:"0063",t:"psychic"},
  "Kadabra": {d:"0064",t:"psychic"},
  "Alakazam": {d:"0065",t:"psychic"},
  "Machop": {d:"0066",t:"fighting"},
  "Machoke": {d:"0067",t:"fighting"},
  "Machamp": {d:"0068",t:"fighting"},
  "Bellsprout": {d:"0069",t:"grass,poison"},
  "Weepinbell": {d:"0070",t:"grass,poison"},
  "Victreebel": {d:"0071",t:"grass,poison"},
  "Tentacool": {d:"0072",t:"water,poison"},
  "Tentacruel": {d:"0073",t:"water,poison"},
  "Geodude": {d:"0074",t:"rock,ground"},
  "Graveler": {d:"0075",t:"rock,ground"},
  "Golem": {d:"0076",t:"rock,ground"},
  "Ponyta": {d:"0077",t:"fire"},
  "Rapidash": {d:"0078",t:"fire"},
  "Slowpoke": {d:"0079",t:"water,psychic"},
  "Slowbro": {d:"0080",t:"water,psychic"},
  "Magnemite": {d:"0081",t:"electric,steel"},
  "Magneton": {d:"0082",t:"electric,steel"},
  "Farfetch\'d": {d:"0083",t:"normal,flying"},
  "Doduo": {d:"0084",t:"normal,flying"},
  "Dodrio": {d:"0085",t:"normal,flying"},
  "Seel": {d:"0086",t:"water"},
  "Dewgong": {d:"0087",t:"water,ice"},
  "Grimer": {d:"0088",t:"poison"},
  "Muk": {d:"0089",t:"poison"},
  "Shellder": {d:"0090",t:"water"},
  "Cloyster": {d:"0091",t:"water,ice"},
  "Gastly": {d:"0092",t:"ghost,poison"},
  "Haunter": {d:"0093",t:"ghost,poison"},
  "Gengar": {d:"0094",t:"ghost,poison"},
  "Onix": {d:"0095",t:"rock,ground"},
  "Drowzee": {d:"0096",t:"psychic"},
  "Hypno": {d:"0097",t:"psychic"},
  "Krabby": {d:"0098",t:"water"},
  "Kingler": {d:"0099",t:"water"},
  "Voltorb": {d:"0100",t:"electric"},
  "Electrode": {d:"0101",t:"electric"},
  "Exeggcute": {d:"0102",t:"grass,psychic"},
  "Exeggutor": {d:"0103",t:"grass,psychic"},
  "Cubone": {d:"0104",t:"ground"},
  "Marowak": {d:"0105",t:"ground"},
  "Hitmonlee": {d:"0106",t:"fighting"},
  "Hitmonchan": {d:"0107",t:"fighting"},
  "Lickitung": {d:"0108",t:"normal"},
  "Koffing": {d:"0109",t:"poison"},
  "Weezing": {d:"0110",t:"poison"},
  "Rhyhorn": {d:"0111",t:"ground,rock"},
  "Rhydon": {d:"0112",t:"ground,rock"},
  "Chansey": {d:"0113",t:"normal"},
  "Tangela": {d:"0114",t:"grass"},
  "Kangaskhan": {d:"0115",t:"normal"},
  "Horsea": {d:"0116",t:"water"},
  "Seadra": {d:"0117",t:"water"},
  "Goldeen": {d:"0118",t:"water"},
  "Seaking": {d:"0119",t:"water"},
  "Staryu": {d:"0120",t:"water"},
  "Starmie": {d:"0121",t:"water,psychic"},
  "Mr. Mime": {d:"0122",t:"psychic"},
  "Scyther": {d:"0123",t:"bug,flying"},
  "Jynx": {d:"0124",t:"ice,psychic"},
  "Electabuzz": {d:"0125",t:"electric"},
  "Magmar": {d:"0126",t:"fire"},
  "Pinsir": {d:"0127",t:"bug"},
  "Tauros": {d:"0128",t:"normal"},
  "Magikarp": {d:"0129",t:"water"},
  "Gyarados": {d:"0130",t:"water,flying"},
  "Lapras": {d:"0131",t:"water,ice"},
  "Ditto": {d:"0132",t:"normal"},
  "Eevee": {d:"0133",t:"normal"},
  "Vaporeon": {d:"0134",t:"water"},
  "Jolteon": {d:"0135",t:"electric"},
  "Flareon": {d:"0136",t:"fire"},
  "Porygon": {d:"0137",t:"normal"},
  "Omanyte": {d:"0138",t:"rock,water"},
  "Omastar": {d:"0139",t:"rock,water"},
  "Kabuto": {d:"0140",t:"rock,water"},
  "Kabutops": {d:"0141",t:"rock,water"},
  "Aerodactyl": {d:"0142",t:"rock,flying"},
  "Snorlax": {d:"0143",t:"normal"},
  "Articuno": {d:"0144",t:"ice,flying"},
  "Zapdos": {d:"0145",t:"electric,flying"},
  "Moltres": {d:"0146",t:"fire,flying"},
  "Dratini": {d:"0147",t:"dragon"},
  "Dragonair": {d:"0148",t:"dragon"},
  "Dragonite": {d:"0149",t:"dragon,flying"},
  "Mewtwo": {d:"0150",t:"psychic"},
  "Mew": {d:"0151",t:"psychic"},
  "Chikorita": {d:"0152",t:"grass"},
  "Bayleef": {d:"0153",t:"grass"},
  "Meganium": {d:"0154",t:"grass"},
  "Cyndaquil": {d:"0155",t:"fire"},
  "Quilava": {d:"0156",t:"fire"},
  "Typhlosion": {d:"0157",t:"fire"},
  "Totodile": {d:"0158",t:"water"},
  "Croconaw": {d:"0159",t:"water"},
  "Feraligatr": {d:"0160",t:"water"},
  "Sentret": {d:"0161",t:"normal"},
  "Furret": {d:"0162",t:"normal"},
  "Hoothoot": {d:"0163",t:"normal,flying"},
  "Noctowl": {d:"0164",t:"normal,flying"},
  "Ledyba": {d:"0165",t:"bug,flying"},
  "Ledian": {d:"0166",t:"bug,flying"},
  "Spinarak": {d:"0167",t:"bug,poison"},
  "Ariados": {d:"0168",t:"bug,poison"},
  "Crobat": {d:"0169",t:"poison,flying"},
  "Chinchou": {d:"0170",t:"water,electric"},
  "Lanturn": {d:"0171",t:"water,electric"},
  "Pichu": {d:"0172",t:"electric"},
  "Cleffa": {d:"0173",t:"normal"},
  "Igglybuff": {d:"0174",t:"normal"},
  "Togepi": {d:"0175",t:"normal"},
  "Togetic": {d:"0176",t:"normal,flying"},
  "Natu": {d:"0177",t:"psychic,flying"},
  "Xatu": {d:"0178",t:"psychic,flying"},
  "Mareep": {d:"0179",t:"electric"},
  "Flaaffy": {d:"0180",t:"electric"},
  "Ampharos": {d:"0181",t:"electric"},
  "Bellossom": {d:"0182",t:"grass"},
  "Marill": {d:"0183",t:"water"},
  "Azumarill": {d:"0184",t:"water"},
  "Sudowoodo": {d:"0185",t:"rock"},
  "Politoed": {d:"0186",t:"water"},
  "Hoppip": {d:"0187",t:"grass,flying"},
  "Skiploom": {d:"0188",t:"grass,flying"},
  "Jumpluff": {d:"0189",t:"grass,flying"},
  "Aipom": {d:"0190",t:"normal"},
  "Sunkern": {d:"0191",t:"grass"},
  "Sunflora": {d:"0192",t:"grass"},
  "Yanma": {d:"0193",t:"bug,flying"},
  "Wooper": {d:"0194",t:"water,ground"},
  "Quagsire": {d:"0195",t:"water,ground"},
  "Espeon": {d:"0196",t:"psychic"},
  "Umbreon": {d:"0197",t:"dark"},
  "Murkrow": {d:"0198",t:"dark,flying"},
  "Slowking": {d:"0199",t:"water,psychic"},
  "Misdreavus": {d:"0200",t:"ghost"},
  "Unown": {d:"0201",t:"psychic"},
  "Wobbuffet": {d:"0202",t:"psychic"},
  "Girafarig": {d:"0203",t:"normal,psychic"},
  "Pineco": {d:"0204",t:"bug"},
  "Forretress": {d:"0205",t:"bug,steel"},
  "Dunsparce": {d:"0206",t:"normal"},
  "Gligar": {d:"0207",t:"ground,flying"},
  "Steelix": {d:"0208",t:"steel,ground"},
  "Snubbull": {d:"0209",t:"normal"},
  "Granbull": {d:"0210",t:"normal"},
  "Qwilfish": {d:"0211",t:"water,poison"},
  "Scizor": {d:"0212",t:"bug,steel"},
  "Shuckle": {d:"0213",t:"bug,rock"},
  "Heracross": {d:"0214",t:"bug,fighting"},
  "Sneasel": {d:"0215",t:"dark,ice"},
  "Teddiursa": {d:"0216",t:"normal"},
  "Ursaring": {d:"0217",t:"normal"},
  "Slugma": {d:"0218",t:"fire"},
  "Magcargo": {d:"0219",t:"fire,rock"},
  "Swinub": {d:"0220",t:"ice,ground"},
  "Piloswine": {d:"0221",t:"ice,ground"},
  "Corsola": {d:"0222",t:"water,rock"},
  "Remoraid": {d:"0223",t:"water"},
  "Octillery": {d:"0224",t:"water"},
  "Delibird": {d:"0225",t:"ice,flying"},
  "Mantine": {d:"0226",t:"water,flying"},
  "Skarmory": {d:"0227",t:"steel,flying"},
  "Houndour": {d:"0228",t:"dark,fire"},
  "Houndoom": {d:"0229",t:"dark,fire"},
  "Kingdra": {d:"0230",t:"water,dragon"},
  "Phanpy": {d:"0231",t:"ground"},
  "Donphan": {d:"0232",t:"ground"},
  "Porygon2": {d:"0233",t:"normal"},
  "Stantler": {d:"0234",t:"normal"},
  "Smeargle": {d:"0235",t:"normal"},
  "Tyrogue": {d:"0236",t:"fighting"},
  "Hitmontop": {d:"0237",t:"fighting"},
  "Smoochum": {d:"0238",t:"ice,psychic"},
  "Elekid": {d:"0239",t:"electric"},
  "Magby": {d:"0240",t:"fire"},
  "Miltank": {d:"0241",t:"normal"},
  "Blissey": {d:"0242",t:"normal"},
  "Raikou": {d:"0243",t:"electric"},
  "Entei": {d:"0244",t:"fire"},
  "Suicune": {d:"0245",t:"water"},
  "Larvitar": {d:"0246",t:"rock,ground"},
  "Pupitar": {d:"0247",t:"rock,ground"},
  "Tyranitar": {d:"0248",t:"rock,dark"},
  "Lugia": {d:"0249",t:"psychic,flying"},
  "Ho-Oh": {d:"0250",t:"fire,flying"},
  "Celebi": {d:"0251",t:"psychic,grass"},
  "Treecko": {d:"0252",t:"grass"},
  "Grovyle": {d:"0253",t:"grass"},
  "Sceptile": {d:"0254",t:"grass"},
  "Torchic": {d:"0255",t:"fire"},
  "Combusken": {d:"0256",t:"fire,fighting"},
  "Blaziken": {d:"0257",t:"fire,fighting"},
  "Mudkip": {d:"0258",t:"water"},
  "Marshtomp": {d:"0259",t:"water,ground"},
  "Swampert": {d:"0260",t:"water,ground"},
  "Poochyena": {d:"0261",t:"dark"},
  "Mightyena": {d:"0262",t:"dark"},
  "Zigzagoon": {d:"0263",t:"normal"},
  "Linoone": {d:"0264",t:"normal"},
  "Wurmple": {d:"0265",t:"bug"},
  "Silcoon": {d:"0266",t:"bug"},
  "Beautifly": {d:"0267",t:"bug,flying"},
  "Cascoon": {d:"0268",t:"bug"},
  "Dustox": {d:"0269",t:"bug,poison"},
  "Lotad": {d:"0270",t:"water,grass"},
  "Lombre": {d:"0271",t:"water,grass"},
  "Ludicolo": {d:"0272",t:"water,grass"},
  "Seedot": {d:"0273",t:"grass"},
  "Nuzleaf": {d:"0274",t:"grass,dark"},
  "Shiftry": {d:"0275",t:"grass,dark"},
  "Taillow": {d:"0276",t:"normal,flying"},
  "Swellow": {d:"0277",t:"normal,flying"},
  "Wingull": {d:"0278",t:"water,flying"},
  "Pelipper": {d:"0279",t:"water,flying"},
  "Ralts": {d:"0280",t:"psychic"},
  "Kirlia": {d:"0281",t:"psychic"},
  "Gardevoir": {d:"0282",t:"psychic"},
  "Surskit": {d:"0283",t:"bug,water"},
  "Masquerain": {d:"0284",t:"bug,flying"},
  "Shroomish": {d:"0285",t:"grass"},
  "Breloom": {d:"0286",t:"grass,fighting"},
  "Slakoth": {d:"0287",t:"normal"},
  "Vigoroth": {d:"0288",t:"normal"},
  "Slaking": {d:"0289",t:"normal"},
  "Nincada": {d:"0290",t:"bug,ground"},
  "Ninjask": {d:"0291",t:"bug,flying"},
  "Shedinja": {d:"0292",t:"bug,ghost"},
  "Whismur": {d:"0293",t:"normal"},
  "Loudred": {d:"0294",t:"normal"},
  "Exploud": {d:"0295",t:"normal"},
  "Makuhita": {d:"0296",t:"fighting"},
  "Hariyama": {d:"0297",t:"fighting"},
  "Azurill": {d:"0298",t:"normal"},
  "Nosepass": {d:"0299",t:"rock"},
  "Skitty": {d:"0300",t:"normal"},
  "Delcatty": {d:"0301",t:"normal"},
  "Sableye": {d:"0302",t:"dark,ghost"},
  "Mawile": {d:"0303",t:"steel"},
  "Aron": {d:"0304",t:"steel,rock"},
  "Lairon": {d:"0305",t:"steel,rock"},
  "Aggron": {d:"0306",t:"steel,rock"},
  "Meditite": {d:"0307",t:"fighting,psychic"},
  "Medicham": {d:"0308",t:"fighting,psychic"},
  "Electrike": {d:"0309",t:"electric"},
  "Manectric": {d:"0310",t:"electric"},
  "Plusle": {d:"0311",t:"electric"},
  "Minun": {d:"0312",t:"electric"},
  "Volbeat": {d:"0313",t:"bug"},
  "Illumise": {d:"0314",t:"bug"},
  "Roselia": {d:"0315",t:"grass,poison"},
  "Gulpin": {d:"0316",t:"poison"},
  "Swalot": {d:"0317",t:"poison"},
  "Carvanha": {d:"0318",t:"water,dark"},
  "Sharpedo": {d:"0319",t:"water,dark"},
  "Wailmer": {d:"0320",t:"water"},
  "Wailord": {d:"0321",t:"water"},
  "Numel": {d:"0322",t:"fire,ground"},
  "Camerupt": {d:"0323",t:"fire,ground"},
  "Torkoal": {d:"0324",t:"fire"},
  "Spoink": {d:"0325",t:"psychic"},
  "Grumpig": {d:"0326",t:"psychic"},
  "Spinda": {d:"0327",t:"normal"},
  "Trapinch": {d:"0328",t:"ground"},
  "Vibrava": {d:"0329",t:"ground,dragon"},
  "Flygon": {d:"0330",t:"ground,dragon"},
  "Cacnea": {d:"0331",t:"grass"},
  "Cacturne": {d:"0332",t:"grass,dark"},
  "Swablu": {d:"0333",t:"normal,flying"},
  "Altaria": {d:"0334",t:"dragon,flying"},
  "Zangoose": {d:"0335",t:"normal"},
  "Seviper": {d:"0336",t:"poison"},
  "Lunatone": {d:"0337",t:"rock,psychic"},
  "Solrock": {d:"0338",t:"rock,psychic"},
  "Barboach": {d:"0339",t:"water,ground"},
  "Whiscash": {d:"0340",t:"water,ground"},
  "Corphish": {d:"0341",t:"water"},
  "Crawdaunt": {d:"0342",t:"water,dark"},
  "Baltoy": {d:"0343",t:"ground,psychic"},
  "Claydol": {d:"0344",t:"ground,psychic"},
  "Lileep": {d:"0345",t:"rock,grass"},
  "Cradily": {d:"0346",t:"rock,grass"},
  "Anorith": {d:"0347",t:"rock,bug"},
  "Armaldo": {d:"0348",t:"rock,bug"},
  "Feebas": {d:"0349",t:"water"},
  "Milotic": {d:"0350",t:"water"},
  "Castform": {d:"0351",t:"normal"},
  "Kecleon": {d:"0352",t:"normal"},
  "Shuppet": {d:"0353",t:"ghost"},
  "Banette": {d:"0354",t:"ghost"},
  "Duskull": {d:"0355",t:"ghost"},
  "Dusclops": {d:"0356",t:"ghost"},
  "Tropius": {d:"0357",t:"grass,flying"},
  "Chimecho": {d:"0358",t:"psychic"},
  "Absol": {d:"0359",t:"dark"},
  "Wynaut": {d:"0360",t:"psychic"},
  "Snorunt": {d:"0361",t:"ice"},
  "Glalie": {d:"0362",t:"ice"},
  "Spheal": {d:"0363",t:"ice,water"},
  "Sealeo": {d:"0364",t:"ice,water"},
  "Walrein": {d:"0365",t:"ice,water"},
  "Clamperl": {d:"0366",t:"water"},
  "Huntail": {d:"0367",t:"water"},
  "Gorebyss": {d:"0368",t:"water"},
  "Relicanth": {d:"0369",t:"water,rock"},
  "Luvdisc": {d:"0370",t:"water"},
  "Bagon": {d:"0371",t:"dragon"},
  "Shelgon": {d:"0372",t:"dragon"},
  "Salamence": {d:"0373",t:"dragon,flying"},
  "Beldum": {d:"0374",t:"steel,psychic"},
  "Metang": {d:"0375",t:"steel,psychic"},
  "Metagross": {d:"0376",t:"steel,psychic"},
  "Regirock": {d:"0377",t:"rock"},
  "Regice": {d:"0378",t:"ice"},
  "Registeel": {d:"0379",t:"steel"},
  "Latias": {d:"0380",t:"dragon,psychic"},
  "Latios": {d:"0381",t:"dragon,psychic"},
  "Kyogre": {d:"0382",t:"water"},
  "Groudon": {d:"0383",t:"ground"},
  "Rayquaza": {d:"0384",t:"dragon,flying"},
  "Jirachi": {d:"0385",t:"steel,psychic"},
  "Deoxys": {d:"0386",t:"psychic"},
  "Turtwig": {d:"0387",t:"grass"},
  "Grotle": {d:"0388",t:"grass"},
  "Torterra": {d:"0389",t:"grass,ground"},
  "Chimchar": {d:"0390",t:"fire"},
  "Monferno": {d:"0391",t:"fire,fighting"},
  "Infernape": {d:"0392",t:"fire,fighting"},
  "Piplup": {d:"0393",t:"water"},
  "Prinplup": {d:"0394",t:"water"},
  "Empoleon": {d:"0395",t:"water,steel"},
  "Starly": {d:"0396",t:"normal,flying"},
  "Staravia": {d:"0397",t:"normal,flying"},
  "Staraptor": {d:"0398",t:"normal,flying"},
  "Bidoof": {d:"0399",t:"normal"},
  "Bibarel": {d:"0400",t:"normal,water"},
  "Kricketot": {d:"0401",t:"bug"},
  "Kricketune": {d:"0402",t:"bug"},
  "Shinx": {d:"0403",t:"electric"},
  "Luxio": {d:"0404",t:"electric"},
  "Luxray": {d:"0405",t:"electric"},
  "Budew": {d:"0406",t:"grass,poison"},
  "Roserade": {d:"0407",t:"grass,poison"},
  "Cranidos": {d:"0408",t:"rock"},
  "Rampardos": {d:"0409",t:"rock"},
  "Shieldon": {d:"0410",t:"rock,steel"},
  "Bastiodon": {d:"0411",t:"rock,steel"},
  "Burmy": {d:"0412",t:"bug"},
  "Wormadam": {d:"0413",t:"bug,grass"},
  "Mothim": {d:"0414",t:"bug,flying"},
  "Combee": {d:"0415",t:"bug,flying"},
  "Vespiquen": {d:"0416",t:"bug,flying"},
  "Pachirisu": {d:"0417",t:"electric"},
  "Buizel": {d:"0418",t:"water"},
  "Floatzel": {d:"0419",t:"water"},
  "Cherubi": {d:"0420",t:"grass"},
  "Cherrim": {d:"0421",t:"grass"},
  "Shellos": {d:"0422",t:"water"},
  "Gastrodon": {d:"0423",t:"water,ground"},
  "Ambipom": {d:"0424",t:"normal"},
  "Drifloon": {d:"0425",t:"ghost,flying"},
  "Drifblim": {d:"0426",t:"ghost,flying"},
  "Buneary": {d:"0427",t:"normal"},
  "Lopunny": {d:"0428",t:"normal"},
  "Mismagius": {d:"0429",t:"ghost"},
  "Honchkrow": {d:"0430",t:"dark,flying"},
  "Glameow": {d:"0431",t:"normal"},
  "Purugly": {d:"0432",t:"normal"},
  "Chingling": {d:"0433",t:"psychic"},
  "Stunky": {d:"0434",t:"poison,dark"},
  "Skuntank": {d:"0435",t:"poison,dark"},
  "Bronzor": {d:"0436",t:"steel,psychic"},
  "Bronzong": {d:"0437",t:"steel,psychic"},
  "Bonsly": {d:"0438",t:"rock"},
  "Mime Jr.": {d:"0439",t:"psychic"},
  "Happiny": {d:"0440",t:"normal"},
  "Chatot": {d:"0441",t:"normal,flying"},
  "Spiritomb": {d:"0442",t:"ghost,dark"},
  "Gible": {d:"0443",t:"dragon,ground"},
  "Gabite": {d:"0444",t:"dragon,ground"},
  "Garchomp": {d:"0445",t:"dragon,ground"},
  "Munchlax": {d:"0446",t:"normal"},
  "Riolu": {d:"0447",t:"fighting"},
  "Lucario": {d:"0448",t:"fighting,steel"},
  "Hippopotas": {d:"0449",t:"ground"},
  "Hippowdon": {d:"0450",t:"ground"},
  "Skorupi": {d:"0451",t:"poison,bug"},
  "Drapion": {d:"0452",t:"poison,dark"},
  "Croagunk": {d:"0453",t:"poison,fighting"},
  "Toxicroak": {d:"0454",t:"poison,fighting"},
  "Carnivine": {d:"0455",t:"grass"},
  "Finneon": {d:"0456",t:"water"},
  "Lumineon": {d:"0457",t:"water"},
  "Mantyke": {d:"0458",t:"water,flying"},
  "Snover": {d:"0459",t:"grass,ice"},
  "Abomasnow": {d:"0460",t:"grass,ice"},
  "Weavile": {d:"0461",t:"dark,ice"},
  "Magnezone": {d:"0462",t:"electric,steel"},
  "Lickilicky": {d:"0463",t:"normal"},
  "Rhyperior": {d:"0464",t:"ground,rock"},
  "Tangrowth": {d:"0465",t:"grass"},
  "Electivire": {d:"0466",t:"electric"},
  "Magmortar": {d:"0467",t:"fire"},
  "Togekiss": {d:"0468",t:"normal,flying"},
  "Yanmega": {d:"0469",t:"bug,flying"},
  "Leafeon": {d:"0470",t:"grass"},
  "Glaceon": {d:"0471",t:"ice"},
  "Gliscor": {d:"0472",t:"ground,flying"},
  "Mamoswine": {d:"0473",t:"ice,ground"},
  "Porygon-Z": {d:"0474",t:"normal"},
  "Gallade": {d:"0475",t:"psychic,fighting"},
  "Probopass": {d:"0476",t:"rock,steel"},
  "Dusknoir": {d:"0477",t:"ghost"},
  "Froslass": {d:"0478",t:"ice,ghost"},
  "Rotom": {d:"0479",t:"electric,ghost"},
  "Uxie": {d:"0480",t:"psychic"},
  "Mesprit": {d:"0481",t:"psychic"},
  "Azelf": {d:"0482",t:"psychic"},
  "Dialga": {d:"0483",t:"steel,dragon"},
  "Palkia": {d:"0484",t:"water,dragon"},
  "Heatran": {d:"0485",t:"fire,steel"},
  "Regigigas": {d:"0486",t:"normal"},
  "Giratina": {d:"0487",t:"ghost,dragon"},
  "Cresselia": {d:"0488",t:"psychic"},
  "Phione": {d:"0489",t:"water"},
  "Manaphy": {d:"0490",t:"water"},
  "Darkrai": {d:"0491",t:"dark"},
  "Shaymin": {d:"0492",t:"grass"},
  "Arceus": {d:"0493",t:"normal"},
  "Victini": {d:"0494",t:"psychic,fire"},
  "Snivy": {d:"0495",t:"grass"},
  "Servine": {d:"0496",t:"grass"},
  "Serperior": {d:"0497",t:"grass"},
  "Tepig": {d:"0498",t:"fire"},
  "Pignite": {d:"0499",t:"fire,fighting"},
  "Emboar": {d:"0500",t:"fire,fighting"},
  "Oshawott": {d:"0501",t:"water"},
  "Dewott": {d:"0502",t:"water"},
  "Samurott": {d:"0503",t:"water"},
  "Patrat": {d:"0504",t:"normal"},
  "Watchog": {d:"0505",t:"normal"},
  "Lillipup": {d:"0506",t:"normal"},
  "Herdier": {d:"0507",t:"normal"},
  "Stoutland": {d:"0508",t:"normal"},
  "Purrloin": {d:"0509",t:"dark"},
  "Liepard": {d:"0510",t:"dark"},
  "Pansage": {d:"0511",t:"grass"},
  "Simisage": {d:"0512",t:"grass"},
  "Pansear": {d:"0513",t:"fire"},
  "Simisear": {d:"0514",t:"fire"},
  "Panpour": {d:"0515",t:"water"},
  "Simipour": {d:"0516",t:"water"},
  "Munna": {d:"0517",t:"psychic"},
  "Musharna": {d:"0518",t:"psychic"},
  "Pidove": {d:"0519",t:"normal,flying"},
  "Tranquill": {d:"0520",t:"normal,flying"},
  "Unfezant": {d:"0521",t:"normal,flying"},
  "Blitzle": {d:"0522",t:"electric"},
  "Zebstrika": {d:"0523",t:"electric"},
  "Roggenrola": {d:"0524",t:"rock"},
  "Boldore": {d:"0525",t:"rock"},
  "Gigalith": {d:"0526",t:"rock"},
  "Woobat": {d:"0527",t:"psychic,flying"},
  "Swoobat": {d:"0528",t:"psychic,flying"},
  "Drilbur": {d:"0529",t:"ground"},
  "Excadrill": {d:"0530",t:"ground,steel"},
  "Audino": {d:"0531",t:"normal"},
  "Timburr": {d:"0532",t:"fighting"},
  "Gurdurr": {d:"0533",t:"fighting"},
  "Conkeldurr": {d:"0534",t:"fighting"},
  "Tympole": {d:"0535",t:"water"},
  "Palpitoad": {d:"0536",t:"water,ground"},
  "Seismitoad": {d:"0537",t:"water,ground"},
  "Throh": {d:"0538",t:"fighting"},
  "Sawk": {d:"0539",t:"fighting"},
  "Sewaddle": {d:"0540",t:"bug,grass"},
  "Swadloon": {d:"0541",t:"bug,grass"},
  "Leavanny": {d:"0542",t:"bug,grass"},
  "Venipede": {d:"0543",t:"bug,poison"},
  "Whirlipede": {d:"0544",t:"bug,poison"},
  "Scolipede": {d:"0545",t:"bug,poison"},
  "Cottonee": {d:"0546",t:"grass"},
  "Whimsicott": {d:"0547",t:"grass"},
  "Petilil": {d:"0548",t:"grass"},
  "Lilligant": {d:"0549",t:"grass"},
  "Basculin": {d:"0550",t:"water"},
  "Sandile": {d:"0551",t:"ground,dark"},
  "Krokorok": {d:"0552",t:"ground,dark"},
  "Krookodile": {d:"0553",t:"ground,dark"},
  "Darumaka": {d:"0554",t:"fire"},
  "Darmanitan": {d:"0555",t:"fire"},
  "Maractus": {d:"0556",t:"grass"},
  "Dwebble": {d:"0557",t:"bug,rock"},
  "Crustle": {d:"0558",t:"bug,rock"},
  "Scraggy": {d:"0559",t:"dark,fighting"},
  "Scrafty": {d:"0560",t:"dark,fighting"},
  "Sigilyph": {d:"0561",t:"psychic,flying"},
  "Yamask": {d:"0562",t:"ghost"},
  "Cofagrigus": {d:"0563",t:"ghost"},
  "Tirtouga": {d:"0564",t:"water,rock"},
  "Carracosta": {d:"0565",t:"water,rock"},
  "Archen": {d:"0566",t:"rock,flying"},
  "Archeops": {d:"0567",t:"rock,flying"},
  "Trubbish": {d:"0568",t:"poison"},
  "Garbodor": {d:"0569",t:"poison"},
  "Zorua": {d:"0570",t:"dark"},
  "Zoroark": {d:"0571",t:"dark"},
  "Minccino": {d:"0572",t:"normal"},
  "Cinccino": {d:"0573",t:"normal"},
  "Gothita": {d:"0574",t:"psychic"},
  "Gothorita": {d:"0575",t:"psychic"},
  "Gothitelle": {d:"0576",t:"psychic"},
  "Solosis": {d:"0577",t:"psychic"},
  "Duosion": {d:"0578",t:"psychic"},
  "Reuniclus": {d:"0579",t:"psychic"},
  "Ducklett": {d:"0580",t:"water,flying"},
  "Swanna": {d:"0581",t:"water,flying"},
  "Vanillite": {d:"0582",t:"ice"},
  "Vanillish": {d:"0583",t:"ice"},
  "Vanilluxe": {d:"0584",t:"ice"},
  "Deerling": {d:"0585",t:"normal,grass"},
  "Sawsbuck": {d:"0586",t:"normal,grass"},
  "Emolga": {d:"0587",t:"electric,flying"},
  "Karrablast": {d:"0588",t:"bug"},
  "Escavalier": {d:"0589",t:"bug,steel"},
  "Foongus": {d:"0590",t:"grass,poison"},
  "Amoonguss": {d:"0591",t:"grass,poison"},
  "Frillish": {d:"0592",t:"water,ghost"},
  "Jellicent": {d:"0593",t:"water,ghost"},
  "Alomomola": {d:"0594",t:"water"},
  "Joltik": {d:"0595",t:"bug,electric"},
  "Galvantula": {d:"0596",t:"bug,electric"},
  "Ferroseed": {d:"0597",t:"grass,steel"},
  "Ferrothorn": {d:"0598",t:"grass,steel"},
  "Klink": {d:"0599",t:"steel"},
  "Klang": {d:"0600",t:"steel"},
  "Klinklang": {d:"0601",t:"steel"},
  "Tynamo": {d:"0602",t:"electric"},
  "Eelektrik": {d:"0603",t:"electric"},
  "Eelektross": {d:"0604",t:"electric"},
  "Elgyem": {d:"0605",t:"psychic"},
  "Beheeyem": {d:"0606",t:"psychic"},
  "Litwick": {d:"0607",t:"ghost,fire"},
  "Lampent": {d:"0608",t:"ghost,fire"},
  "Chandelure": {d:"0609",t:"ghost,fire"},
  "Axew": {d:"0610",t:"dragon"},
  "Fraxure": {d:"0611",t:"dragon"},
  "Haxorus": {d:"0612",t:"dragon"},
  "Cubchoo": {d:"0613",t:"ice"},
  "Beartic": {d:"0614",t:"ice"},
  "Cryogonal": {d:"0615",t:"ice"},
  "Shelmet": {d:"0616",t:"bug"},
  "Accelgor": {d:"0617",t:"bug"},
  "Stunfisk": {d:"0618",t:"ground,electric"},
  "Mienfoo": {d:"0619",t:"fighting"},
  "Mienshao": {d:"0620",t:"fighting"},
  "Druddigon": {d:"0621",t:"dragon"},
  "Golett": {d:"0622",t:"ground,ghost"},
  "Golurk": {d:"0623",t:"ground,ghost"},
  "Pawniard": {d:"0624",t:"dark,steel"},
  "Bisharp": {d:"0625",t:"dark,steel"},
  "Bouffalant": {d:"0626",t:"normal"},
  "Rufflet": {d:"0627",t:"normal,flying"},
  "Braviary": {d:"0628",t:"normal,flying"},
  "Vullaby": {d:"0629",t:"dark,flying"},
  "Mandibuzz": {d:"0630",t:"dark,flying"},
  "Heatmor": {d:"0631",t:"fire"},
  "Durant": {d:"0632",t:"bug,steel"},
  "Deino": {d:"0633",t:"dark,dragon"},
  "Zweilous": {d:"0634",t:"dark,dragon"},
  "Hydreigon": {d:"0635",t:"dark,dragon"},
  "Larvesta": {d:"0636",t:"bug,fire"},
  "Volcarona": {d:"0637",t:"bug,fire"},
  "Cobalion": {d:"0638",t:"steel,fighting"},
  "Terrakion": {d:"0639",t:"rock,fighting"},
  "Virizion": {d:"0640",t:"grass,fighting"},
  "Tornadus": {d:"0641",t:"flying"},
  "Thundurus": {d:"0642",t:"electric,flying"},
  "Reshiram": {d:"0643",t:"dragon,fire"},
  "Zekrom": {d:"0644",t:"dragon,electric"},
  "Landorus": {d:"0645",t:"ground,flying"},
  "Kyurem": {d:"0646",t:"dragon,ice"},
  "Keldeo": {d:"0647",t:"water,fighting"},
  "Meloetta": {d:"0648",t:"normal,psychic"},
  "Genesect": {d:"0649",t:"bug,steel"},
  "Enamorus": {d:"0905",t:"flying"}
};

/* ── Trainer class → sprite filename aliases ── */
/* Use these when the class name typed in data-trainer doesn't match the file exactly.
   For most trainers, data-trainer already matches the filename (e.g. "Guitarist" → Guitarist.png).
   Add aliases here only for special / abbreviated filenames. */
const TRAINER_ALIASES = {
  "Ace Trainer F":       "Ace_F",
  "Ace Trainer M":       "Ace_M",
  "Ace Trainer F G5":    "Ace_F_G5",
  "Ace Trainer M G5":    "Ace_M_G5",
  "Ace Trainer F Wint":  "Ace_F_Wint",
  "Ace Trainer M Wint":  "Ace_M_Wint",
  "Aroma Lady":          "AromaLady",
  "Artist F":            "Artist_F",
  "Artist M":            "Artist_M",
  "Backpacker F":        "Backpacker_F",
  "Backpacker M":        "Backpacker_M",
  "Battle Girl":         "BattleGIrl",
  "Bird Keeper F":       "BirdKeeper_F",
  "Bird Keeper M":       "BirdKeeper_M",
  "Black Belt":          "BlackBelt",
  "Blueberry F":         "Blueberry_F",
  "Blueberry M":         "Blueberry_M",
  "Bug Catcher":         "BugCatcher",
  "Butterfly Catcher":   "ButterflyCatcher",
  "Cleric F":            "Cleric_F",
  "Cleric M":            "Cleric_M",
  "Cyclist F":           "Cyclist_F",
  "Cyclist M":           "Cyclist_M",
  "Dragon Tamer":        "DragonTamer",
  "Fairytale Girl":      "FairytaleGirl",
  "Galactic Boss":       "Galactic Boss",
  "Galaxias Grunt F":    "Glx_G_F",
  "Galaxias Grunt M":    "Glx_G_M",
  "Galaxias Boss F":     "Glx_B_F",
  "Galaxias Boss M":     "Glx_B_M",
  "Galaxias Purple F":   "Glx_P_F",
  "Galaxias Purple M":   "Glx_P_M",
  "Galaxias Red F":      "Glx_R_F",
  "Galaxias Red M":      "Glx_R_M",
  "Hex Maniac":          "Hexmaniac",
  "ICI F":               "ICI_F",
  "ICI M":               "ICI_M",
  "Parasol Lady":        "ParasolLady",
  "Pokefan F":           "Pokefan_F",
  "Pokefan M":           "Pokefan_M",
  "Pokemon Breeder F":   "PokemonBreeder_F",
  "Pokemon Breeder M":   "PokemonBreeder_M",
  "Pokemon Ranger F":    "PokemonRanger_F",
  "Pokemon Ranger M":    "PokemonRanger_M",
  "Psychic F":           "Psychic_F",
  "Psychic M":           "Psychic_M",
  "Punkster F":          "Punkster_F",
  "Punkster M":          "Punkster_M",
  "Rail Staff":          "RailStaff",
  "Researcher F":        "Researcher_F",
  "Researcher M":        "Researcher_M",
  "Ruin Maniac":         "RuinManiac",
  "Security Guard":      "SecurityGuard",
  "Skier F":             "Skier_F",
  "Skier M":             "Skier_M",
  "Student F":           "Student_F",
  "Student M":           "Student_M",
  "Swimmer F":           "Swimmer_F",
  "Swimmer M":           "Swimmer_M",
  "Teacher F":           "Teacher_F",
  "Teacher M":           "Teacher_M",
  "Tech Maniac":         "TechManiac",
  "Trainer F":           "Trainer_F",
  "Trainer M":           "Trainer_M",
  "TrainerDP F":         "TrainerDP_F",
  "TrainerDP M":         "TrainerDP_M",
  "Veteran F":           "Veteran_F",
  "Veteran M":           "Veteran_M",
  "White Collar F":      "WhiteCollar_F",
  "White Collar M":      "WhiteCollar_M",
  "Worker SM":           "Worker_SM",
  "Worker Wint":         "Worker_Wint"
};

/* ═══════════════════════════════════════════
   WIKI_NAV — Page manifest for sidebar navigation.
   Keys are section labels; each entry is { href, title }.
   Paths are relative to the wiki root.
   ═══════════════════════════════════════════ */
const WIKI_NAV = {
  "Cities": [
    { href: "Locations/Cities/Solaceon.html",              title: "Solaceon Town" },
    { href: "Locations/Cities/Veilstone.html",             title: "Veilstone City" }
  ],
  "Routes": [
    { href: "Locations/Routes/Route_205.html",             title: "Route 205" },
    { href: "Locations/Routes/Route_206.html",             title: "Route 206" },
    { href: "Locations/Routes/Route_207.html",             title: "Route 207" },
    { href: "Locations/Routes/Route_208.html",             title: "Route 208" },
    { href: "Locations/Routes/Route_209.html",             title: "Route 209" },
    { href: "Locations/Routes/Route_210.html",             title: "Route 210" },
    { href: "Locations/Routes/Route_211.html",             title: "Route 211" },
    { href: "Locations/Routes/Route_215.html",             title: "Route 215" },
    { href: "Locations/Routes/Route_216.html",             title: "Route 216" },
    { href: "Locations/Routes/Route_217.html",             title: "Route 217" }
  ],
  "Dungeons": [
    { href: "Locations/Dungeons/Galaxias_Labs.html",       title: "Galaxias Labs" },
    { href: "Locations/Dungeons/Galaxias_Pilot_Plant.html",title: "Galaxias Pilot Plant" },
    { href: "Locations/Dungeons/Veilstain.html",           title: "The Veilstain" },
    { href: "Locations/Dungeons/Solaceon_Ruins.html",      title: "Solaceon Ruins" },
    { href: "Locations/Dungeons/The_Miragescape.html",     title: "The Miragescape" },
    { href: "Locations/Dungeons/Abandoned_Warehouse.html", title: "Abandoned Warehouse" },
    { href: "Locations/Dungeons/Mount_Coronet.html",       title: "Mount Coronet" }
  ],
  "Landmarks": [
    { href: "Locations/Landmarks/Meerou_Exhibition.html",  title: "Meerou Exhibition" },
    { href: "Locations/Landmarks/Pristine_Lounge.html",    title: "Pristine Lounge" },
    { href: "Locations/Landmarks/Rapidash_Ranch.html",     title: "Rapidash Ranch" },
    { href: "Locations/Landmarks/Veilstone_Harbor.html",   title: "Veilstone Harbor" },
    { href: "Locations/Landmarks/Galerie_Pradau.html",     title: "Galerie Pradau" },
    { href: "Locations/Landmarks/DreamLab.html",           title: "DreamLab" },
    { href: "Locations/Landmarks/Lily_Park.html",          title: "Lily Park" },
    { href: "Locations/Landmarks/Windrose_Cliffs.html",    title: "Windrose Cliffs" },
    { href: "Locations/Landmarks/Lustrous_Academy.html",   title: "Lustrous Academy" },
    { href: "Locations/Landmarks/Celestica_Memorial.html", title: "Celestica Memorial" }
  ],
  "Shops": [
    { href: "Locations/Shops/Veilstone_Marketplace.html",  title: "Veilstone Marketplace" },
    { href: "Locations/Shops/Solace_Cafe.html",            title: "Solace Café" },
    { href: "Locations/Shops/Coronet_Apothecary.html",     title: "Coronet Apothecary" }
  ],
  "Docs": [
    { href: "Docs/Climate_System.html",  title: "Climate System" },
    { href: "Docs/Credits.html",         title: "Credits" },
    { href: "Docs/Homebase.html",        title: "Homebase" },
    { href: "Docs/Item_List.html",       title: "Item List" },
    { href: "Docs/Moves_List.html",      title: "Moves List" },
    { href: "Docs/NPCs.html",            title: "NPCs" },
    { href: "Docs/Phenomena.html",       title: "Phenomena" },
    { href: "Docs/Pokedex.html",         title: "Pokédex" },
    { href: "Docs/Pokemon.html",         title: "Pokémon" },
    { href: "Docs/Spacetime.html",       title: "Spacetime" }
  ]
};